name: Validate main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: |
        python3 -m pip install --user pip --upgrade pylint
        pylint quickdocs.py

    - name: Validate
      run: python3 -m quickdocs --withcss
